CREATE DATABASE stwa_elixir_dev;

\c stwa_elixir_dev;

CREATE TABLE IF NOT EXISTS paragraphs (
    id SERIAL PRIMARY KEY,
    paragraph text NOT NULL UNIQUE,
		chapter integer NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

INSERT INTO paragraphs (id, paragraph, chapter) VALUES
(1, 'Of the things which are in our Power, and not in our Power', 1),
(2, 'Of all the faculties, you will find not one which is capable of contemplating itself; and, consequently, not capable either of approving or disapproving. How far does the grammatic art possess the contemplating power? As far as forming a judgement about what is written and spoken. And how far music? As far as judging about melody. Does either of them then contemplate itself? By no means. But when you must write something to your friend, grammar will tell you what words you must write; but whether you should write or not, grammar will not tell you. And so it is with music as to musical sounds; but whether you should sing at the present time and play on the lute, or do neither, music will not tell you. What faculty then will tell you? That which contemplates both itself and all other things. And what is this faculty? The rational faculty; for this is the only faculty that we have received which examines itself, what it is, and what power it has, and what is the value of this gift, and examines all other faculties: for what else is there which tells us that golden things are beautiful, for they do not say so themselves? Evidently it is the faculty which is capable of judging of appearances. What else judges of music, grammar, and other faculties, proves their uses and points out the occasions for using them? Nothing else.', 1),
(3, 'As then it was fit to be so, that which is best of all and supreme over all is the only thing which the gods have placed in our power, the right use of appearances; but all other things they have not placed in our power. Was it because they did not choose? I indeed think that, if they had been able, they would have put these other things also in our power, but they certainly could not. For as we exist on the earth, and are bound to such a body and to such companions, how was it possible for us not to be hindered as to these things by externals?', 1),
(4, 'But what says Zeus? "Epictetus, if it were possible, I would have made both your little body and your little property free and not exposed to hindrance. But now be not ignorant of this: this body is not yours, but it is clay finely tempered. And since I was not able to do for you what I have mentioned, I have given you a small portion of us, this faculty of pursuing an object and avoiding it, and the faculty of desire and aversion, and, in a word, the faculty of using the appearances of things; and if you will take care of this faculty and consider it your only possession, you will never be hindered, never meet with impediments; you will not lament, you will not blame, you will not flatter any person."', 1),
(5, '"Well, do these seem to you small matters?" I hope not. "Be content with them then and pray to the gods." But now when it is in our power to look after one thing, and to attach ourselves to it, we prefer to look after many things, and to be bound to many things, to the body and to property, and to brother and to friend, and to child and to slave. Since, then, we are bound to many things, we are depressed by them and dragged down. For this reason, when the weather is not fit for sailing, we sit down and torment ourselves, and continually look out to see what wind is blowing. "It is north." What is that to us? "When will the west wind blow?" When it shall choose, my good man, or when it shall please AEolus; for God has not made you the manager of the winds, but AEolus. What then? We must make the best use that we can of the things which are in our power, and use the rest according to their nature. What is their nature then? As God may please.', 1),
(6, '"Must I, then, alone have my head cut off?" What, would you have all men lose their heads that you may be consoled? Will you not stretch out your neck as Lateranus did at Rome when Nero ordered him to be beheaded? For when he had stretched out his neck, and received a feeble blow, which made him draw it in for a moment, he stretched it out again. And a little before, when he was visited by Epaphroditus, Nero`s freedman, who asked him about the cause of offense which he had given, he said, "If I choose to tell anything, I will tell your master."', 1)
